name: gl_gh_client
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  github: ^9.7.0
  gl_gh_common:
    path: ../gl_gh_common
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_web_socket: ^1.0.3
  web_socket_channel: ^2.2.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.16.0
