name: gl_gh_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  github: ^9.7.0
  json_annotation: ^4.7.0
  retry: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lint: ^2.0.1
