name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - run: curl "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64" --output "gitlab-runner"
    
    - run: chmod +x gitlab-runner
    
    - run: ./gitlab-runner run-single -u https://gitlab.com -t zSDqT5QbJ7G1VVPJvfyT --executor docker --docker-image ruby:2.7 --max-builds 1 --wait-timeout 10
