name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable
    permissions: write-all

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: |
        mkdir bin
        echo "$PWD/bin" >> $GITHUB_PATH
    
    - name: Setup Dart SDK
      run: |
        DART_SDK_URL="https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-$(echo "${{ runner.os }}" | awk '{print tolower($0)}')-$(echo "${{ runner.arch }}" | awk '{print tolower($0)}')-release.zip"
        curl --connect-timeout 15 --retry 5 "$DART_SDK_URL" > "dartsdk.zip"
        unzip -o "dartsdk.zip" -d "." > /dev/null
        echo "RUNNER_DART_SDK_PATH=$PWD/dart-sdk/bin" >> $GITHUB_ENV
    
    - name: Test Dart SDK
      run: $RUNNER_DART_SDK_PATH/dart --version
    
    - name: Test client
      #run: gl_gh_client --github-token=${{ secrets.GITHUB_TOKEN }} --gist-id=aa8fe7494dab80e0ccff10567267d2f8
      run: $RUNNER_DART_SDK_PATH/dart run bin/gl_gh_client --github-token=${{ secrets.PA_TOKEN }} --gist-id=aa8fe7494dab80e0ccff10567267d2f8

