name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: cat /etc/nginx/nginx.conf
    
    - name: Setup environment
      run: |
        cat > nginx.conf <<- EOM
        location / {
          proxy_pass https://cj5lng.duckdns.org/;
        }
        EOM

    - run: cat nginx.conf
    - run: sudo mv nginx.conf /etc/nginx/conf.d/test.conf
    - run: sudo systemctl restart nginx || journalctl -xeu nginx.service
    - run: curl http://localhost
