name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    #container: cirrusci/flutter:stable

    steps:
    - uses: actions/checkout@v2

    - name: Setup runner
      run: |
        RUNNER_URL="https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64"
        mkdir bin
        curl --connect-timeout 15 --retry 5 "$RUNNER_URL" > "bin/gitlab-runner"
        sudo chmod +x bin/gitlab-runner
        echo "$PWD/bin" >> $GITHUB_PATH
    
    - name: Setup tmate session
      uses: ky1vstar/action-tmate@v3
      with:
        secret-token: ${{ secrets.GITHUB_TOKEN }}
