name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Dart SDK
      env:
        DART_SDK_URL: "https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-${{ runner.os }}-x64-release.zip"
      run: |
        curl --connect-timeout 15 --retry 5 "$DART_SDK_URL" > "dartsdk.zip"
        unzip -o "dartsdk.zip" -d "." > /dev/null
        ./dart-sdk/bin/dart --version
