name: CI

on: push

jobs:
  test:
    runs-on: macos-latest
    
    env:
      KEYCHAIN_NAME: builds.keychain
      KEYCHAIN_PASSWORD: alpine
      FL_IMPORT_CERT_KEYCHAIN_PASSWORD: ${{ env.KEYCHAIN_PASSWORD }}
      MATCH_KEYCHAIN_NAME: ${{ env.KEYCHAIN_NAME }}
      MATCH_KEYCHAIN_PASSWORD: ${{ env.KEYCHAIN_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    
    - uses: subosito/flutter-action@v2
      with:
        cache: true
    
    - name: Setup FVM
      run: dart pub global activate fvm
      
    - uses: acorn-io/actions-setup-keychain@v1.0
      with:
        name: ${{ env.KEYCHAIN_NAME }}
        password: ${{ env.KEYCHAIN_PASSWORD }}

    - name: Setup environment
      run: echo "$PWD/test" >> $GITHUB_PATH
    
    - name: Run tests for client
      run: dart run test/gl_gh_client --github-token=${{ secrets.PA_TOKEN }} --storage-id=885805cc28c7f840fca999ca00de66b3
