name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: |
        echo "$PWD/bin" >> $GITHUB_PATH
        echo "RUNNER_DART_SDK_PATH=$PWD/dart-sdk/bin" >> $GITHUB_ENV
    
    - name: Setup Dart SDK
      run: |
        DART_SDK_URL="https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-$(echo "${{ runner.os }}" | awk '{print tolower($0)}')-$(echo "${{ runner.arch }}" | awk '{print tolower($0)}')-release.zip"
        wget --timeout=15 --tries=5 --quiet -O "dartsdk.zip" "$DART_SDK_URL"
        unzip -o "dartsdk.zip" -d "." > /dev/null
    
    - name: Test Dart SDK
      run: $RUNNER_DART_SDK_PATH/dart --version
    
    - name: Test client
      #run: gl_gh_client --github-token=${{ secrets.GITHUB_TOKEN }} --gist-id=6da722e2ddaf69acb867756bf179cb79
      run: $RUNNER_DART_SDK_PATH/dart run bin/gl_gh_client --github-token=${{ secrets.PA_TOKEN }} --gist-id=6da722e2ddaf69acb867756bf179cb79

