name: CI

on: push

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: subosito/flutter-action@v2
    
    - name: Setup FVM
      run: dart pub global activate fvm

    - name: Setup environment
      run: echo "$PWD/test" >> $GITHUB_PATH
    
    - name: Run tests for client
      run: dart run test/gl_gh_client --github-token=${{ secrets.PA_TOKEN }} --storage-id=9982797bfda59778a9b7eaa678f6d8b4
