name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:stable
      options: --label "type=main"
    services:
      helper:
        image: bitnami/git
        options: --label "type=helper" --entrypoint "tail" --it

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: echo "$PWD/test" >> $GITHUB_PATH
    
    - name: Run tests for client
      run: gl_gh_client --github-token=${{ secrets.PA_TOKEN }} --storage-id=94a69576cbec8f86e60adb5480c648b1

