name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup environment
      run: |
        curl -L --output gitlab-runner "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64"
        sudo chmod +x gitlab-runner
    
    - run: gitlab-runner run-single --url http://7.tcp.eu.ngrok.io:13227/gl --token keklol --executor docker --max-builds 1 --wait-timeout 10
