name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: stedolan/jq

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup environment
      run: |
        echo "\$PWD/test" >> \$GITHUB_PATH
        cd ~
        unset HOME
        
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
