name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    #container: cirrusci/flutter:stable

    steps:
    - uses: actions/checkout@v2

    - name: Setup Dart SDK
      run: |
        echo "ENV_1=123" >> $GITHUB_ENV

    - name: Setup runner ${{ env.ENV_1 }}
      run: |
        RUNNER_URL="https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64"
        mkdir bin
        curl --connect-timeout 15 --retry 5 "$RUNNER_URL" > "bin/gitlab-runner"
        sudo chmod +x bin/gitlab-runner
        echo "$PWD/bin" >> $GITHUB_PATH

    - name: Test runner ${{ env.ENV_2 }}
      run: |
        echo "ENV_2=321" >> $GITHUB_ENV
        ping 127.0.0.1
    
    - name: Setup tmate session ${{ env.ENV_2 }}
      uses: mxschmitt/action-tmate@v3
